---
- hosts: all
  become: true
  
  tasks:
  - pause: seconds=60

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Install Python3
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - python3-minimal

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Copy the access token to server location
    copy: src=access_token_command dest=/tmp/access_token_command mode=0777

  - name: Copy the k3s install script to server location
    copy: src=k3s-worker-install.sh dest=/tmp/k3s-worker-install.sh remote_src=no mode=0777

  - name: Copy the script to combine token and k3s install to server location
    copy: src=combine-scripts.sh dest=/tmp/combine-scripts.sh remote_src=no mode=0777

  - name: Install K3S on worker
    command: "{{ item }}"
    with_items:
     - bash /tmp/combine-scripts.sh
     - bash /tmp/k3s-install.sh

  handlers:
   - name: docker status
     service: name=docker state=started